FROM node:14.21.3 AS dev-deps
WORKDIR /app
COPY package*.json ./
RUN npm install

FROM node:14.21.3 AS builder
WORKDIR /app
COPY --from=dev-deps /app/node_modules /app/node_modules
COPY . .
RUN npm run build

FROM nginx:1.21.3 as prod
EXPOSE 4201
COPY --from=builder /app/dist/Frontend /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]